services:
  - type: web
    name: ibizi
    env: python
    buildCommand: bash build.sh
    startCommand: bash -c "python manage.py migrate --noinput; gunicorn config.wsgi:application --log-file - --access-logfile -"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: DEBUG
        value: "False"
      - key: USE_SQLITE_FALLBACK
        value: "True"