"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from django.contrib.messages import constants as messages
import os
import dj_database_url
from dotenv import load_dotenv

# Р—Р°РіСЂСѓР¶Р°РµРј РїРµСЂРµРјРµРЅРЅС‹Рµ РѕРєСЂСѓР¶РµРЅРёСЏ РёР· .env С„Р°Р№Р»Р°
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-1amkr^tiy*k_$#!i75mt15-0*sospg8wi(n&o31$f(3#y2ko(y')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = ['ibizi.pythonanywhere.com', '127.0.0.1', 'localhost', '.onrender.com', 'ibizi.onrender.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'albedo',  # РґРѕР±Р°РІР»СЏРµРј РЅР°С€Рµ РїСЂРёР»РѕР¶РµРЅРёРµ
    'cloudinary_storage',  # Cloudinary РґР»СЏ С…СЂР°РЅРµРЅРёСЏ С„Р°Р№Р»РѕРІ
    'cloudinary',  # Cloudinary РґР»СЏ СЂР°Р±РѕС‚С‹ СЃ РјРµРґРёР°
]

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

#CACHE_MIDDLEWARE_SECONDS = 900  # 15 РјРёРЅСѓС‚
#CACHE_MIDDLEWARE_KEY_PREFIX = ''  # Р”РѕР±Р°РІСЊС‚Рµ РїСЂРµС„РёРєСЃ, РµСЃР»Рё РЅСѓР¶РЅРѕ

MIDDLEWARE = [
    #'django.middleware.cache.UpdateCacheMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Р”РѕР±Р°РІР»СЏРµРј WhiteNoise РґР»СЏ РѕР±СЂР°Р±РѕС‚РєРё СЃС‚Р°С‚РёС‡РµСЃРєРёС… С„Р°Р№Р»РѕРІ
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'albedo.middleware.UserBlockStatusMiddleware',  # Middleware РґР»СЏ Р±Р»РѕРєРёСЂРѕРІРєРё РїРѕР»СЊР·РѕРІР°С‚РµР»РµР№Р»СЊР·РѕРІР°С‚РµР»РµР№
    'albedo.middleware.SecurityHeadersMiddleware',  # РќРѕРІС‹Р№ middleware РґР»СЏ Р·Р°РіРѕР»РѕРІРєРѕРІ Р±РµР·РѕРїР°СЃРЅРѕСЃС‚Рё
    'albedo.middleware.PathTraversalProtectionMiddleware', # Р—Р°С‰РёС‚Р° РѕС‚ path traversal
    #'django.middleware.cache.FetchFromCacheMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# РљР°СЃС‚РѕРјРЅС‹Рµ РѕР±СЂР°Р±РѕС‚С‡РёРєРё РѕС€РёР±РѕРє
HANDLER404 = 'albedo.views.custom_404_view'

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# РќР°СЃС‚СЂРѕР№РєР° РґР»СЏ Render.com: РёСЃРїРѕР»СЊР·РѕРІР°РЅРёРµ PostgreSQL РІ РїСЂРѕРґР°РєС€РЅ-СЃСЂРµРґРµ
DATABASE_URL = os.environ.get('DATABASE_URL')
if DATABASE_URL:
    DATABASES['default'] = dj_database_url.config(default=DATABASE_URL, conn_max_age=600)


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Asia/Krasnoyarsk'

USE_I18N = True

USE_TZ = True

# amoCRM Settings
AMOCRM_SUBDOMAIN = 'buqame'  
AMOCRM_TOKEN = os.environ.get('AMOCRM_TOKEN', 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjZhYmI1YmFkMzNkZGRmNmM3NDg0M2IyNWNhMGY4ZTViNmIxYmI4ODlhZTE2MzRmMjk0NTBjMGYzMzY4ZDJiZmJlY2RiMDUxNTY3ZjBmZjk3In0.eyJhdWQiOiJmNDQ1MWVmNS0wZTM5LTRlYmItYjViZS00OTQyYjAxNDUwOWYiLCJqdGkiOiI2YWJiNWJhZDMzZGRkZjZjNzQ4NDNiMjVjYTBmOGU1YjZiMWJiODg5YWUxNjM0ZjI5NDUwYzBmMzM2OGQyYmZiZWNkYjA1MTU2N2YwZmY5NyIsImlhdCI6MTc3NjkzNTg5MywibmJmIjoxNzc2OTM1ODkzLCJleHAiOjE3NzcwMjIyOTMsInN1YiI6IjEzNzQ2NDgyIiwiZ3JhbnRfdHlwZSI6IiIsImFjY291bnRfaWQiOjMzMDE3NjY2LCJiYXNlX2RvbWFpbiI6ImFtb2NybS5ydSIsInZlcnNpb24iOjIsInNjb3BlcyI6WyJwdXNoX25vdGlmaWNhdGlvbnMiLCJmaWxlcyIsImNybSIsImZpbGVzX2RlbGV0ZSIsIm5vdGlmaWNhdGlvbnMiXSwiaGFzaF91dWlkIjoiY2FlYjc3NjMtYWQzNi00MzhkLWJkY2ItZWFkODNlZWFhNjE1IiwiYXBpX2RvbWFpbiI6ImFwaS1iLmFtb2NybS5ydSJ9.TMpOfnJgSDkDUKc3HfD2hDAY36AJ4gGdPSCeZrsj1aCazQsGr0CRJtr2Fiflo9u981IH0TvVzoK-KQQ1UB5Ri7lSpqWWCCIZpmwqhwSj7Koos0Dm4XcuEC21YxExBi8EH0mfS96Mr098qkHTAJ5ZCLfhPdYJtuFUOe-2zmGtfT4-0hKjdGLMf9BY0JzWyudRBK_sqBAaLVc3qUuggWuFdjDJDM0ZhVqvr3RYhBP8EQI3FXJjsE5l9DnmofpYQlpZE4hu0rY6wVHF-Jm7cKofVBJpNs4Ipmq6L_L38UaUqVSj0sYEj8KWDW4jWytetX9a0bWFYdp1uDTzYq7OKN_dMQ')
AMOCRM_SECRET_TOKEN = os.environ.get('AMOCRM_SECRET_TOKEN', 'fRcGvRrqP5lEOS4FAAzSvnVP25hpS1mNn9rjpOySLbpJSHtKgimPmoDEZukxaHEc')
AMOCRM_INTEGRATION_ID = 'f4451ef5-0e39-4ebb-b5be-4942b014509f'
AMOCRM_SECRET_TOKEN = os.environ.get('AMOCRM_SECRET_TOKEN', 'fRcGvRrqP5lEOS4FAAzSvnVP25hpS1mNn9rjpOySLbpJSHtKgimPmoDEZukxaHEc')
AMOCRM_INTEGRATION_ID = 'f4451ef5-0e39-4ebb-b5be-4942b014509f'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'  # РћР±СЂР°С‚РёС‚Рµ РІРЅРёРјР°РЅРёРµ РЅР° СЃР»РµС€ РІ РЅР°С‡Р°Р»Рµ Рё РІ РєРѕРЅС†Рµ
STATICFILES_DIRS = [
    BASE_DIR / 'albedo' / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (Uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

load_dotenv(os.path.join(BASE_DIR, "config", ".env"))

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.mail.ru'
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'albedo.User'

MESSAGE_TAGS = {
    messages.DEBUG: 'alert-secondary',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}

# Authentication settings
LOGIN_REDIRECT_URL = 'profile'  # URL РґР»СЏ РїРµСЂРµРЅР°РїСЂР°РІР»РµРЅРёСЏ РїРѕСЃР»Рµ СѓСЃРїРµС€РЅРѕРіРѕ РІС…РѕРґР°
LOGIN_URL = 'login'  # URL РґР»СЏ РїРµСЂРµРЅР°РїСЂР°РІР»РµРЅРёСЏ, РµСЃР»Рё С‚СЂРµР±СѓРµС‚СЃСЏ Р°СѓС‚РµРЅС‚РёС„РёРєР°С†РёСЏ


LOGOUT_REDIRECT_URL = 'home'  # URL РґР»СЏ РїРµСЂРµРЅР°РїСЂР°РІР»РµРЅРёСЏ РїРѕСЃР»Рµ РІС‹С…РѕРґР°# File upload security settings
ALLOWED_UPLOAD_EXTENSIONS = ['.jpg', '.jpeg', '.png', '.gif', '.pdf', '.doc', '.docx', '.xls', '.xlsx', '.txt', '.zip']
MAX_UPLOAD_SIZE = 10 * 1024 * 1024  # 10MB

# Р”РѕРїРѕР»РЅРёС‚РµР»СЊРЅС‹Рµ РЅР°СЃС‚СЂРѕР№РєРё Р±РµР·РѕРїР°СЃРЅРѕСЃС‚Рё
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'
SESSION_COOKIE_SECURE = True  # Р’ production РёР·РјРµРЅРёС‚СЊ РЅР° True
CSRF_COOKIE_SECURE = True  # Р’ production РёР·РјРµРЅРёС‚СЊ РЅР° True

# РќР°СЃС‚СЂРѕР№РєРё РґР»СЏ СЃС‚Р°С‚РёС‡РµСЃРєРёС… С„Р°Р№Р»РѕРІ
if not DEBUG:
    # Р’РєР»СЋС‡Р°РµРј HTTPS-РЅР°СЃС‚СЂРѕР№РєРё РґР»СЏ РїСЂРѕРґР°РєС€РЅ-СЃСЂРµРґС‹
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # РСЃРїРѕР»СЊР·СѓРµРј WhiteNoise РґР»СЏ СЃР¶Р°С‚РёСЏ Рё С…СЌС€РёСЂРѕРІР°РЅРёСЏ СЃС‚Р°С‚РёС‡РµСЃРєРёС… С„Р°Р№Р»РѕРІ РІ РїСЂРѕРґР°РєС€РЅ
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
else:
    # Р”Р»СЏ СЂРµР¶РёРјР° СЂР°Р·СЂР°Р±РѕС‚РєРё РёСЃРїРѕР»СЊР·СѓРµРј РѕР±С‹С‡РЅРѕРµ С…СЂР°РЅРёР»РёС‰Рµ
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

# РќР°СЃС‚СЂРѕР№РєРё РґР»СЏ С…СЂР°РЅРµРЅРёСЏ С„Р°Р№Р»РѕРІ
USE_CLOUDINARY = False  # РћС‚РєР»СЋС‡Р°РµРј Cloudinary

# Cloudinary РЅР°СЃС‚СЂРѕР№РєРё (СЃРѕС…СЂР°РЅСЏРµРј, РµСЃР»Рё РїРѕРЅР°РґРѕР±СЏС‚СЃСЏ РїРѕР·Р¶Рµ)
if USE_CLOUDINARY:
    import cloudinary
    import cloudinary.uploader
    import cloudinary.api
    
    cloudinary.config(
        cloud_name=os.environ.get('CLOUDINARY_CLOUD_NAME', ''),
        api_key=os.environ.get('CLOUDINARY_API_KEY', ''),
        api_secret=os.environ.get('CLOUDINARY_API_SECRET', ''),
        secure=True
    )
    
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME', ''),
        'API_KEY': os.environ.get('CLOUDINARY_API_KEY', ''),
        'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET', ''),
    }
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
else:
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
