# Generated by Django 5.1.6 on 2025-04-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albedo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='cloudinary_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('admin', 'Администратор')], default='user', max_length=5),
        ),
    ]
