# Generated by Django 5.1.6 on 2025-04-14 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albedo', '0002_file_cloudinary_url_alter_user_role'),
    ]

    operations = [
    ]
