# Generated by Django 5.1.6 on 2025-04-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albedo', '0003_auto_20250414_1541'),
    ]

    operations = [
        # Удаляем поле, если оно существует (это не вызовет ошибку, если поля нет)
        migrations.RemoveField(
            model_name='file',
            name='cloudinary_url',
        ),
        
        # Добавляем поле заново
        migrations.AddField(
            model_name='file',
            name='cloudinary_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
