# Generated by Django 5.1.6 on 2025-04-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albedo', '0004_alter_event_options_alter_file_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, max_length=300, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=28, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='file',
            name='mime_type',
            field=models.CharField(max_length=255, verbose_name='MIME тип'),
        ),
    ]
