# Generated by Django 5.1.6 on 2025-04-14 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albedo', '0004_fix_cloudinary_url'),
    ]

    operations = [
    ]
