# Generated by Django 5.1.6 on 2025-05-14 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albedo', '0005_alter_event_description_alter_event_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('attempt_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
