# Generated by Django 5.1.6 on 2025-04-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albedo', '0006_postgres_fix_cloudinary_url'),
    ]

    operations = [
        # Прямой SQL-запрос для PostgreSQL
        migrations.RunSQL(
            # SQL для выполнения, адаптированный для PostgreSQL
            """
            DO $$
            BEGIN
                BEGIN
                    -- Проверяем существует ли колонка preview_url
                    IF NOT EXISTS (
                        SELECT 1 
                        FROM information_schema.columns 
                        WHERE table_name = 'albedo_file' 
                        AND column_name = 'preview_url'
                    ) THEN
                        -- Добавляем колонку, если ее нет
                        ALTER TABLE albedo_file ADD COLUMN preview_url varchar(1000) NULL;
                    END IF;
                EXCEPTION
                    WHEN OTHERS THEN
                        -- Игнорируем любые ошибки
                        NULL;
                END;
            END $$;
            """,
            # SQL для отмены миграции (можно оставить пустым)
            ""
        ),
    ]