# Generated by Django 5.1.6 on 2026-05-28 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albedo', '0007_alter_event_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='cloudinary_url',
        ),
        migrations.RemoveField(
            model_name='file',
            name='preview_url',
        ),
    ]
